# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PS_OC_cnodejs' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PS_OC_cnodejs

  target 'PS_OC_cnodejsTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SDWebImage'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'FMDB'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'MWPhotoBrowser'
  pod 'WMPageController'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  pod 'YYKit'
  pod 'CocoaLumberjack', '~> 2.2.0'
  pod 'ReactiveCocoa', '~> 2.5'
#  pod 'UMengAnalytics', '~> 3.6.6'
  pod 'LKDBHelper'

  target 'PS_OC_cnodejsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
